# Generated by Django 4.2.6 on 2023-10-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='username',
            new_name='name',
        ),
    ]
