# Generated by Django 4.2.6 on 2023-10-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_rename_username_appuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='name',
            new_name='username',
        ),
    ]
