# Generated by Django 4.2.6 on 2023-10-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_tips', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrustworthyWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustworthy_website_url', models.URLField()),
                ('trustworthy_website_status', models.CharField(choices=[('Secure', 'Secure'), ('Suspicious', 'Suspicious')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnregisteredScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('link_url', models.URLField()),
                ('link_status', models.CharField(choices=[('Secure', 'Secure'), ('Suspicious', 'Suspicious')], max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('reasons_for_verification', models.TextField()),
                ('recommended_actions', models.TextField()),
                ('additional_info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('domain_status', models.CharField(choices=[('Secure', 'Secure'), ('Suspicious', 'Suspicious')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
