# Generated by Django 4.2.6 on 2023-10-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkverify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unregisteredscan',
            old_name='link_url',
            new_name='url',
        ),
    ]
