# Generated by Django 4.2.6 on 2023-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkverify', '0002_rename_link_url_unregisteredscan_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unregisteredscan',
            old_name='status',
            new_name='url_status',
        ),
    ]
