# Generated by Django 4.2.6 on 2023-10-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkverify', '0003_rename_status_unregisteredscan_url_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkverification',
            name='link_status',
            field=models.CharField(choices=[(1, 'Secure'), (0, 'Suspicious')], max_length=50),
        ),
    ]
