# Generated by Django 4.2.6 on 2023-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkverify', '0004_alter_linkverification_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredscan',
            name='url_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
